---

#mkfs.ext4 -F -L nixos /dev/md126p1
- name: create / device
  filesystem:
    fstype: ext4
    dev: /dev/md126p1
    opts: -F -L nixos

- name: Mount / device
  mount:
    path: /mnt
    src: LABEL=nixos
    fstype: ext4
    state: mounted

#mkfs.fat -F 32 -n boot /dev/md127p1
- name: create /boot device
  filesystem:
    fstype: ext4
    dev: /dev/md127p1
    opts: -F 32 -n boot

- name: Mount /boot device
  mount:
    path: /mnt
    src: LABEL=boot
    fstype: fat32
    state: mounted

- name: generate configuration.nix template
  command: nixos-generate-config --root /mnt
  register: result

- name: create configuration.nix
  template:
    src: configuration.nix.j2
    dest: /mnt/etc/nixos/configuration.nix
    owner: root
    group: root
    mode: 0644

- name: install nixos
  command: nixos-install --no-root-passwd
  register: result
