---

- name: generate configuration.nix template
  command: nixos-generate-config --root /mnt
  register: result

- name: create configuration.nix
  template:
    src: configuration.nix.j2
    dest: /mnt/etc/nixos/configuration.nix
    owner: root
    group: root
    mode: 0644

- name: install nixos
  command: nixos-install --no-root-passwd
  register: result

- name: create  /home/nouma/.ssh
  file:
    path: /mnt/home/nouma/.ssh
    # owner: nouma
    # group: nouma
    state: directory

- name: create /home/nouma/.ssh/authorized_keys
  template:
    src: home/nouma/.ssh/authorized_keys.j2
    dest: /mnt/home/nouma/.ssh/authorized_keys
    # owner: nouma
    # group: nouma
    mode: 600
