---

#- name: unconditionally reboot the machine with all defaults
#  shell: "/run/current-system/sw/bin/shutdown -r now"
#
#- name: wait for 30s for reboot to finish
#  # This pause is mandatory, otherwise the existing control connection gets reused!
#  pause: seconds=30
#
#- name: check if the machine is up again
#  # Now we will run a local 'ansible -m ping' on this host until it returns.
#  # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
#  local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
#  register: result
#  until: result.rc == 0
#  retries: 30
#  delay: 10
#
#- name: print uptime
#  # And finally, execute 'uptime' when the host is back.
#  shell: uptime
#
##- name: upgrade os
##  command: nixos-rebuild switch --upgrade
##  register: result
